# See https://docs.spring.io/spring-cloud-openfeign/docs/current/reference/html/
spring:
  application:
    name: yangfan-core-api
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

foo:
  url: http://localhost:8090

logging:
  pattern:
    level: "%5p [${spring.application.name:}, %X{traceId:-}, %X{spanId:-}]"

---
spring:
  config:
    activate:
      on-profile: default,local,dev,test

logging:
  level:
    io.github.yangfan.core.foo: DEBUG